// web/src/screens/earn/Host.tsx
'use client'

import { useEffect, useState, useCallback } from 'react'

import Link from 'next/link'

import { usePlausible } from 'next-plausible'

import sdk, { type FrameContext } from '@farcaster/frame-sdk'

import {
    useAccount,
    useWriteContract,
    useWaitForTransactionReceipt,
    // useSwitchChain,
    // useChainId,
} from 'wagmi'
import { BaseError, UserRejectedRequestError } from 'viem'

import { abi } from '~/abi/CastPoker'

import { Asset } from '~/components/ui/host/Asset'
import { Button } from '~/components/ui/Button'
import { BuyIn } from '~/components/ui/host/BuyIn'
import { DeckType } from '~/components/ui/host/DeckType'
import { GameType } from '~/components/ui/host/GameType'
import { Network } from '~/components/ui/host/Network'
// import { Optional } from '~/components/ui/host/Optional'
import { Seating } from '~/components/ui/host/Seating'

import { truncateAddress } from '~/lib/truncateAddress'

const renderError = (error: Error | null) => {
    if (!error) return null

    if (error instanceof BaseError) {
        const isUserRejection = error.walk((e) => e instanceof UserRejectedRequestError)

        if (isUserRejection) {
            return <div className="text-red-500 text-xs mt-1">Rejected by user.</div>
        }
    }

    return <div className="text-red-500 text-xs mt-1">{error.message}</div>
}

/* Set constants. */
const CAST_POKER_CONTRACT_ADDR = '0x3Dabb4d559C176ee7A149222404Af0deB7f8e889'

export default function Host({ tableid }: { tableid: string}) {
    const [isSDKLoaded, setIsSDKLoaded] = useState(false)
    const [context, setContext] = useState<FrameContext>()
    const [txHash, setTxHash] = useState<string | null>(null)

    const [asset, setAsset] = useState('eth')
    const [buyIn, setBuyIn] = useState('100000000000000')
    const [deckType, setDeckType] = useState('single')
    const [gameType, setGameType] = useState('community')
    const [network, setNetwork] = useState('base')
    const [token, setToken] = useState<`0x${string}`>('0x0000000000000000000000000000000000000000')
    const [timeToSit, setTimeToSit] = useState('86400')
    // const [tableName, setTableName] = useState('')

    const plausible = usePlausible()
    const { address, isConnected } = useAccount()
    // const chainId = useChainId()

//     const handleTableName = useCallback((event) => {
// console.log('HANDLE TABLE NAME', event.target.value)
//         setTableName(event.target.value)
//     }, [ tableName ])

    const handleBuyIn = useCallback((event: React.ChangeEvent<HTMLSelectElement>) => {
        setBuyIn(event.target.value)
    }, [])

    const handleAsset = useCallback((event: React.ChangeEvent<HTMLSelectElement>) => {
        return console.log('ASSET IS CURRENTLY RESTRICTED!')
        setAsset(event.target.value)
    }, [])

    const handleDeckType = useCallback((event: string) => {
        return console.log('DECK TYPE IS CURRENTLY RESTRICTED!')
        setDeckType(event)
    }, [])

    const handleGameType = useCallback((event: string) => {
        return console.log('GAME TYPE IS CURRENTLY RESTRICTED!')
        setGameType(event)
    }, [])

    const handleNetwork = useCallback((event: string) => {
        return console.log('NETWORK IS CURRENTLY RESTRICTED!')
        setNetwork(event)
    }, [])

    const handleSeating = useCallback((event: React.ChangeEvent<HTMLSelectElement>) => {
        setTimeToSit(event.target.value)
    }, [])

    const {
        writeContract,
        error: sendTxError,
        isError: isSendTxError,
        isPending: isSendTxPending,
    } = useWriteContract()

    const { isLoading: isConfirming, isSuccess: isConfirmed } =
        useWaitForTransactionReceipt({
            hash: txHash as `0x${string}`,
        })

    useEffect(() => {
        const load = async () => {
            setContext(await sdk.context)
            sdk.actions.ready()
        }

        if (sdk && !isSDKLoaded) {
            setIsSDKLoaded(true)
            load()
        }
    }, [ isSDKLoaded ])

    useEffect(() => {
        if (asset === 'eth') {
            setToken('0x0000000000000000000000000000000000000000')
        }

        if (asset === 'degen') {
            setToken('0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed')
        }
    }, [ asset ])

    if (!isSDKLoaded) {
        return <div>Loading. Please wait...</div>
    }

    /**
     * Create Venue
     *
     * Executes either a new Bench or Table in the CasinoPoker contract.
     */
    const _handleCreateVenue = async () => {
        /* Build package. */
        const pkg = {
            gameType,
            deckType,
            network,
            asset,
            buyIn,
            timeToSit,
        }

        /* Track new venues. */
        plausible('createVenue', {
            props: {
                user: context?.user,
                tableid,
                ...pkg,
            },
        })

// return alert(JSON.stringify(pkg, null, 2))

        /* Set function name. */
        const functionName = gameType === 'community' ? 'setTable' : 'setBench'

// TODO Allow host to set their own seed.
        const seed = 0n
// TODO Allow host to set max seating.
        const numSeats = 23
// FIXME Change fomo to a boolean.
        const fomo = deckType === 'single' ? 0 : 1
// TODO Allow host to set their own theme.
        const theme = 0

        /* Make on-chain execution request. */
        writeContract(
            {
                abi,
                address: CAST_POKER_CONTRACT_ADDR,
                functionName,
                args: [
                    token,              // token
                    seed,               // seed
                    BigInt(buyIn),      // buy-in
                    BigInt(timeToSit),  // tts
                    numSeats,           // seats
                    fomo,               // fomo
                    theme,              // theme
                ],
            },
            {
                onSuccess: (hash) => {
console.log('TRANSACTION SUCCESSFUL', hash)
                    setTxHash(hash)
                },
            }
        )
    }

    return (
        <main className="w-full">
            <section>
                <div className="border-b border-gray-200">
                    <nav className="-mb-px flex" aria-label="Tabs">
                        {/* <!-- Current: "border-indigo-500 text-indigo-600", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" --> */}
                        <Link href={`/${tableid}/share`} className="w-1/2 border-b-2 border-transparent px-1 py-4 text-center text-lg font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">
                            Promotion
                        </Link>

                        <Link href={`/${tableid}/host`} className="w-1/2 border-b-2 border-indigo-500 px-1 py-4 text-center text-lg font-medium text-indigo-600" aria-current="page">
                            Hosting
                        </Link>
                    </nav>
                </div>
            </section>

            <section className="my-5 px-3">
                <div className="w-full flex justify-center">
                    <h1 className="sm:px-10 text-4xl font-light text-rose-400 text-center italic leading-[55px]">
                        {context?.user.displayName || 'Guest'}, Earn <span className="text-5xl font-bold">5%</span> Of ALL Table Buy-ins By Hosting
                    </h1>
                </div>

                <p className="my-4 text-slate-700">
                    Cast Casino offers the <span className="font-bold">EASIEST</span> referral rewards in all of Farcaster!
                    Simply recast <span className="font-bold">ANY</span> of our table games and you&rsquo;re done!
                </p>

                <ol className="pl-10 list-decimal text-slate-700">
                    <li>
                        Earn <span className="text-xl font-bold text-rose-500">5%</span> on <span className="font-bold">EVERY</span> dollar wagered on your table .. <span className="font-bold">WIN or LOSE!</span>
                    </li>

                    <li>
                        Payouts are sent <span className="font-bold">DIRECTLY</span> to your Farcaster wallet
                    </li>

                    <li>
                        Payouts are sent <span className="font-bold">IMMEDIATELY</span> after play ends
                    </li>
                </ol>
            </section>

            <div className="flex flex-col gap-2">
                <GameType
                    value={gameType}
                    onClick={handleGameType}
                />

                <DeckType
                    value={deckType}
                    onClick={handleDeckType} />

                <Network
                    value={network}
                    onClick={handleNetwork} />

                <Asset
                    value={asset}
                    onChange={handleAsset} />

                <BuyIn
                    value={buyIn}
                    onChange={handleBuyIn} />

                <Seating
                    value={timeToSit}
                    onChange={handleSeating} />
            </div>

            {/* <div className="my-10 mx-10 border-t border-slate-300" /> */}

            {/* <Optional
                tableName={tableName}
                handleTableName={handleTableName}
            /> */}

            <section className="mt-5 mb-10 text-center">
                <Button
                    onClick={_handleCreateVenue}
                    // disabled={!isConnected || isSendTxPending}
                    disabled={isSendTxPending}
                    isLoading={isSendTxPending}
                    className="text-2xl font-bold tracking-wider"
                >
                    Create My Table
                </Button>

                {isConnected && <div>
                    My address is {address}
                </div>}

                {isSendTxError && renderError(sendTxError)}

                {txHash && (
                    <div className="mt-2 text-xs">
                        <div className="">
                            Hash: {truncateAddress(txHash)}
                        </div>

                        <div className="">
                            Status :&nbsp;
                            {isConfirming
                                ? 'Confirming...'
                                : isConfirmed
                                    ? 'Confirmed!'
                                    : 'Pending'}
                        </div>
                    </div>
                )}
            </section>
        </main>
    )
}

// pages/[tableid]/Host.vue
<template>
    <main class="w-full">
        <section>
            <div class="border-b border-gray-200">
                <nav class="-mb-px flex" aria-label="Tabs">
                    <!-- Current: "border-indigo-500 text-indigo-600", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
                    <NuxtLink :href="`/${tableid}/share`" class="w-1/2 border-b-2 border-transparent px-1 py-4 text-center text-lg font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">
                        Promotion
                    </NuxtLink>

                    <NuxtLink :href="`/${tableid}/host`" class="w-1/2 border-b-2 border-indigo-500 px-1 py-4 text-center text-lg font-medium text-indigo-600" aria-current="page">
                        Hosting
                    </NuxtLink>
                </nav>
            </div>
        </section>

        <section class="my-5 px-3">
            <div class="w-full flex justify-center">
                <h1 class="sm:px-10 text-4xl font-light text-rose-400 text-center italic leading-[55px]">
                    {{user?.displayName || 'Guest'}}, Earn <span class="text-5xl font-bold">5%</span> Of
                    <br />ALL Table Buy-ins By Hosting
                </h1>
            </div>

            <p class="my-4 text-slate-700">
                Cast Casino offers the <span class="font-bold">EASIEST</span> referral rewards in all of Farcaster!
                Simply recast <span class="font-bold">ANY</span> of our table games and you&rsquo;re done!
            </p>

            <ol class="pl-10 list-decimal text-slate-700">
                <li>
                    Earn <span class="text-xl font-bold text-rose-500">5%</span> on <span class="font-bold">EVERY</span> dollar wagered on your table .. <span class="font-bold">WIN or LOSE!</span>
                </li>

                <li>
                    Payouts are sent <span class="font-bold">DIRECTLY</span> to your Farcaster wallet
                </li>

                <li>
                    Payouts are sent <span class="font-bold">IMMEDIATELY</span> after play ends
                </li>
            </ol>
        </section>

        <div class="flex flex-col gap-2">
            <GameType
                :value="gameType"
                @click="handleGameType"
            />

            <DeckType
                :value="deckType"
                @click="handleDeckType" />

            <Network
                :value="network"
                @click="handleNetwork" />

            <Asset
                :value="asset"
                @change="handleAsset" />

            <BuyIn
                :token="token"
                :value="buyIn"
                @change="handleBuyIn" />

            <Seating
                :value="timeToSit"
                @change="handleSeating" />
        </div>

        <!-- <div class="my-10 mx-10 border-t border-slate-300" /> -->

        <!-- <Optional
            tableName={tableName}
            handleTableName={handleTableName}
        /> -->

        <section class="mt-5 mb-10 text-center">
            <button
                @click="_handleCreateVenue"
                :disabled="isSendTxPending"
                :isLoading="isSendTxPending"
                class="text-2xl font-bold tracking-wider"
            >
                Create My Table
            </button>

            <div v-if="isConnected">
                My address is {{address}}
            </div>

            {{isSendTxError && renderError(sendTxError)}}

            <div v-if="txHash" class="mt-2 text-xs">
                <div class="">
                    Hash: {{truncateAddress(txHash)}}
                </div>

                <div class="">
                    Status :&nbsp;
                    {{isConfirming
                        ? 'Confirming...'
                        : isConfirmed
                            ? 'Confirmed!'
                            : 'Pending'}}
                </div>
            </div>
        </section>
    </main>
</template>

<script setup lang="ts">
/* Import modules. */
import sdk, { type FrameContext } from '@farcaster/frame-sdk'
import { BaseError, UserRejectedRequestError } from 'viem'

// import {
//     useAccount,
//     useWriteContract,
//     useWaitForTransactionReceipt,
//     // useSwitchChain,
//     // useChainId,
// } from 'wagmi'

import castPokerAbi from '../../abi/CastPoker'
import { truncateAddress } from '../../libs/truncateAddress'

/* Initialize route. */
const route = useRoute()

// FIXME Validate table ID -- redirect if needed

/* Initialize table ID. */
const tableid = ref<number>(Number(route.params.tableid))

/* Build frame embed. */
const frame = {
    version: 'next',
    imageUrl: `https://og-table.cast.poker/${tableid.value}`,
    button: {
        title: `Hosting`,
        action: {
            type: 'launch_frame',
            name: `Host a Game of Poker`,
            url: `https://cast.poker/${tableid.value}/host/`,
            splashImageUrl: `https://cast.poker/splash.gif`,
            splashBackgroundColor: '#cd98f9',
        },
    },
}

/* Set page title + meta tags. */
useHead({
    title: 'Hosting — Cast Poker',
    meta: [
        { name: 'description', content: 'Cast Poker offers a premium blockchain gaming experience for Players over 18+.' },
        { name: 'fc:frame', content: JSON.stringify(frame) },
    ],
})

type User = {
    displayName: string;
}

const isConfirming = ref<boolean>(false)
const isConfirmed = ref<boolean>(false)
const isConnected = ref<boolean>(false)
const isSendTxError = ref<boolean>(false)

const sendTxError = ref<Error | null>()
// const txHash = ref<string>()
const user = ref<User>()

const renderError = (error: Error | null | undefined) => {
    if (!error) return null

    if (error instanceof BaseError) {
        const isUserRejection = error.walk((e) => e instanceof UserRejectedRequestError)

        if (isUserRejection) {
            return `<div class="text-red-500 text-xs mt-1">Rejected by user.</div>`
        }
    }

    return `<div class="text-red-500 text-xs mt-1">${error.message}</div>`
}

/* Set constants. */
const CAST_POKER_ADDRESS = '0x3Dabb4d559C176ee7A149222404Af0deB7f8e889'

const txHash = ref<string | null>(null)

const asset = ref<string | null>('eth')
const buyIn = ref<string | null>('100000000000000')
const deckType = ref<string | null>('single')
const gameType = ref<string | null>('community')
const network = ref<string | null>('base')
const token = ref<`0x${string}`>('0x0000000000000000000000000000000000000000')
const timeToSit = ref<string | null>('86400')
// const tableName = ref<string | null>('')

// const handleBuyIn = useCallback((event: React.ChangeEvent<HTMLSelectElement>) => {
//     setBuyIn(event.target.value)
// }, [])

// const handleAsset = useCallback((event: React.ChangeEvent<HTMLSelectElement>) => {
//     console.log('ASSET IS CURRENTLY RESTRICTED!')
//     setAsset(event.target.value)
// }, [])

// const handleDeckType = useCallback((event: string) => {
//     return console.log('DECK TYPE IS CURRENTLY RESTRICTED!')
//     setDeckType(event)
// }, [])

// const handleGameType = useCallback((event: string) => {
//     return console.log('GAME TYPE IS CURRENTLY RESTRICTED!')
//     setGameType(event)
// }, [])

// const handleNetwork = useCallback((event: string) => {
//     return console.log('NETWORK IS CURRENTLY RESTRICTED!')
//     setNetwork(event)
// }, [])

// const handleSeating = useCallback((event: React.ChangeEvent<HTMLSelectElement>) => {
//     setTimeToSit(event.target.value)
// }, [])

</script>
