// web/src/app/[tableid]/page.tsx
import moment from 'moment'
import { Metadata } from 'next'
import App from '~/app/app'

const appUrl = process.env.NEXT_PUBLIC_URL

interface Props {
    params: Promise<{
        tableid: string
    }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { tableid } = await params

    const frame = {
        version: 'next',
        imageUrl: `${appUrl}/${tableid}/opengraph-image?${moment().unix()}`,
        button: {
            title: 'Watch Table',
            action: {
                type: 'launch_frame',
                name: 'Table — Cast Poker',
                url: `${appUrl}/${tableid}/`,
                splashImageUrl: `${appUrl}/splash.gif`,
                splashBackgroundColor: '#f7f7f7',
            },
        },
    }

    return {
        title: `Poker Table # ${tableid} — Cast Poker`,
        description: `Come play a hand of poker at table # ${tableid}`,
        openGraph: {
            title: `Poker Table # ${tableid} — Cast Poker`,
            description: `Come play a hand of poker at table # ${tableid}`,
        },
        other: {
            'fc:frame': JSON.stringify(frame),
        },
    }
}

export default async function TableFrame({ params }: Props) {
    const { tableid } = await params

    return <App screenid={'table'} tableid={tableid} />
}

// pages/[tableid]/index.vue
<template>
    <main class="bg-white">
        <Table v-if="screenid === 'table'" :tableid="tableid" />

        <!--
        {screenid === 'agent' && <Agent tableid={tableid} />}
        {screenid === 'fairplay' && <Fairplay tableid={tableid} />}
        {screenid === 'faq' && <Faq tableid={tableid} />}
        {screenid === 'host' && <Host tableid={tableid} />}
        {screenid === 'mysuite' && <MySuite tableid={tableid} />}
        {screenid === 'lounge' && <Lounge tableid={tableid} />}
        {screenid === 'share' && <Share tableid={tableid} />}
        {screenid === 'concierge' && <Concierge tableid={tableid} />}
        -->
    </main>
</template>

<script setup lang="ts">
const DEFAULT_TABLE_ID = 1337

const route = useRoute()
console.log(route.params)

const screenid = ref<string>('table')
const tableid = ref<number>(Number(route.params.tableid) || DEFAULT_TABLE_ID)
console.log('TABLE ID', tableid.value)

const frame = {
    version: 'next',
    imageUrl: `https://og-table.cast.poker/${tableid.value}`,
    button: {
        title: `Watch Table #${tableid.value}`,
        action: {
            type: 'launch_frame',
            name: `Table #${tableid.value} — Cast Poker`,
            url: `https://cast.poker/${tableid.value}/`,
            splashImageUrl: `https://cast.poker/splash.gif`,
            splashBackgroundColor: '#35654d',
        },
    },
}

useHead({
    title: 'Cast Poker — Casual Blockchain Gaming',
    meta: [
        { name: 'description', content: 'Cast Poker offers a premium blockchain gaming experience for Players over 18+.' },
        { name: 'fc:frame', content: JSON.stringify(frame) },
    ],
})
</script>
