// components/FullDeck.vue
<template>
    <main class="w-full py-4 flex flex-col gap-8">

        <section class="grid grid-cols-7 gap-1">

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/AS.svg"
                    alt="Ace-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #0
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/KS.svg"
                    alt="King-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #1
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/QS.svg"
                    alt="Queen-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #2
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/JS.svg"
                    alt="Jack-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #3
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/TS.svg"
                    alt="Ten-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #4
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/9S.svg"
                    alt="Nine-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #5
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/8S.svg"
                    alt="Eight-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #6
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/7S.svg"
                    alt="Seven-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #7
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/6S.svg"
                    alt="Six-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #8
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/5S.svg"
                    alt="Five-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #9
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/4S.svg"
                    alt="Four-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #10
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/3S.svg"
                    alt="Three-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #11
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/2S.svg"
                    alt="Two-of-Spades"
                />

                <span class="text-xs flex justify-center">
                    #12
                </span>
            </div>
        </section>

        <section class="grid grid-cols-7 gap-1">

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/AH.svg"
                    alt="Ace-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #13
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/KH.svg"
                    alt="King-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #14
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/QH.svg"
                    alt="Queen-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #15
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/JH.svg"
                    alt="Jack-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #16
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/TH.svg"
                    alt="Ten-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #17
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/9H.svg"
                    alt="Nine-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #18
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/8H.svg"
                    alt="Eight-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #19
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/7H.svg"
                    alt="Seven-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #20
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/6H.svg"
                    alt="Six-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #21
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/5H.svg"
                    alt="Five-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #22
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/4H.svg"
                    alt="Four-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #23
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/3H.svg"
                    alt="Three-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #24
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/2H.svg"
                    alt="Two-of-Hearts"
                />

                <span class="text-xs flex justify-center">
                    #25
                </span>
            </div>
        </section>

        <section class="grid grid-cols-7 gap-1">

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/AC.svg"
                    alt="Ace-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #26
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/KC.svg"
                    alt="King-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #27
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/QC.svg"
                    alt="Queen-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #28
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/JC.svg"
                    alt="Jack-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #29
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/TC.svg"
                    alt="Ten-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #30
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/9C.svg"
                    alt="Nine-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #31
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/8C.svg"
                    alt="Eight-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #32
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/7C.svg"
                    alt="Seven-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #33
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/6C.svg"
                    alt="Six-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #34
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/5C.svg"
                    alt="Five-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #35
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/4C.svg"
                    alt="Four-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #36
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/3C.svg"
                    alt="Three-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #37
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/2C.svg"
                    alt="Two-of-Clubs"
                />

                <span class="text-xs flex justify-center">
                    #38
                </span>
            </div>
        </section>

        <section class="grid grid-cols-7 gap-1">

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/AD.svg"
                    alt="Ace-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #39
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/KD.svg"
                    alt="King-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #40
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/QD.svg"
                    alt="Queen-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #41
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/JD.svg"
                    alt="Jack-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #42
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/TD.svg"
                    alt="Ten-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #43
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/9D.svg"
                    alt="Nine-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #44
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/8D.svg"
                    alt="Eight-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #45
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/7D.svg"
                    alt="Seven-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #46
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/6D.svg"
                    alt="Six-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #47
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/5D.svg"
                    alt="Five-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #48
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/4D.svg"
                    alt="Four-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #49
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/3D.svg"
                    alt="Three-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #50
                </span>
            </div>

            <div class="flex flex-col items-center">
                <img
                    class="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                    src="https://assets.cast.casino/cards_01/2D.svg"
                    alt="Two-of-Diamonds"
                />

                <span class="text-xs flex justify-center">
                    #51
                </span>
            </div>
        </section>

    </main>
</template>

// components/ui/FullDeck.tsx
import Image from 'next/image'

export function FullDeck() {
    return (
        <main className="w-full py-4 flex flex-col gap-8">

            <section className="grid grid-cols-7 gap-1">

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/AS.svg"
                        alt="Ace-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #0
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/KS.svg"
                        alt="King-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #1
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/QS.svg"
                        alt="Queen-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #2
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/JS.svg"
                        alt="Jack-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #3
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/TS.svg"
                        alt="Ten-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #4
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/9S.svg"
                        alt="Nine-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #5
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/8S.svg"
                        alt="Eight-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #6
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/7S.svg"
                        alt="Seven-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #7
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/6S.svg"
                        alt="Six-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #8
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/5S.svg"
                        alt="Five-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #9
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/4S.svg"
                        alt="Four-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #10
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/3S.svg"
                        alt="Three-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #11
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/2S.svg"
                        alt="Two-of-Spades"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #12
                    </span>
                </div>
            </section>

            <section className="grid grid-cols-7 gap-1">

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/AH.svg"
                        alt="Ace-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #13
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/KH.svg"
                        alt="King-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #14
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/QH.svg"
                        alt="Queen-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #15
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/JH.svg"
                        alt="Jack-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #16
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/TH.svg"
                        alt="Ten-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #17
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/9H.svg"
                        alt="Nine-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #18
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/8H.svg"
                        alt="Eight-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #19
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/7H.svg"
                        alt="Seven-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #20
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/6H.svg"
                        alt="Six-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #21
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/5H.svg"
                        alt="Five-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #22
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/4H.svg"
                        alt="Four-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #23
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/3H.svg"
                        alt="Three-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #24
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/2H.svg"
                        alt="Two-of-Hearts"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #25
                    </span>
                </div>
            </section>

            <section className="grid grid-cols-7 gap-1">

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/AC.svg"
                        alt="Ace-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #26
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/KC.svg"
                        alt="King-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #27
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/QC.svg"
                        alt="Queen-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #28
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/JC.svg"
                        alt="Jack-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #29
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/TC.svg"
                        alt="Ten-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #30
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/9C.svg"
                        alt="Nine-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #31
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/8C.svg"
                        alt="Eight-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #32
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/7C.svg"
                        alt="Seven-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #33
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/6C.svg"
                        alt="Six-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #34
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/5C.svg"
                        alt="Five-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #35
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/4C.svg"
                        alt="Four-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #36
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/3C.svg"
                        alt="Three-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #37
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/2C.svg"
                        alt="Two-of-Clubs"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #38
                    </span>
                </div>
            </section>

            <section className="grid grid-cols-7 gap-1">

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/AD.svg"
                        alt="Ace-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #39
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/KD.svg"
                        alt="King-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #40
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/QD.svg"
                        alt="Queen-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #41
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/JD.svg"
                        alt="Jack-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #42
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/TD.svg"
                        alt="Ten-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #43
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/9D.svg"
                        alt="Nine-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #44
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/8D.svg"
                        alt="Eight-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #45
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/7D.svg"
                        alt="Seven-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #46
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/6D.svg"
                        alt="Six-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #47
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/5D.svg"
                        alt="Five-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #48
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/4D.svg"
                        alt="Four-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #49
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/3D.svg"
                        alt="Three-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #50
                    </span>
                </div>

                <div className="flex flex-col items-center">
                    <Image
                        className="mx-5 w-12 sm:w-12 border-2 border-slate-700"
                        src="https://assets.cast.casino/cards_01/2D.svg"
                        alt="Two-of-Diamonds"
                        width={0}
                        height={0}
                    />

                    <span className="text-xs flex justify-center">
                        #51
                    </span>
                </div>
            </section>

        </main>
    )
}
